tap "homebrew/cask-fonts"

brew "git"
brew "stow"
brew "wget"
brew "tmux"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "zsh"
brew "openssl@3"
brew "python@3.12"
brew "node"
brew "neovim"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
