FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    git \
    gnupg \
    make \
    stow \
    sudo \
    tzdata \
    unzip \
    zsh \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
