x-default-env: &default-env
  DOTFILES_PROFILE: ${DOTFILES_PROFILE:-personal}

x-default-service: &default-service
  init: true
  working_dir: /workspace/dotfiles
  environment: *default-env
  volumes:
    - ..:/workspace/dotfiles

name: dotfiles

services:
  ubuntu:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu
    command: sleep infinity

  fedora:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.fedora
    command: sleep infinity

  dev:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/workspace/dotfiles
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/bash
      - -l
