FROM fedora:39

RUN dnf -y upgrade --refresh \
 && dnf -y install \
    bash \
    ca-certificates \
    curl \
    git \
    gnupg2 \
    hostname \
    make \
    stow \
    sudo \
    unzip \
    which \
    zsh \
 && dnf clean all \
 && rm -rf /var/cache/dnf

WORKDIR /workspace
