x-default-env: &default-env
  DOTFILES_PROFILE: ${DOTFILES_PROFILE:-personal}

x-default-service: &default-service
  init: true
  working_dir: /workspace
  environment: *default-env
  volumes:
    - ${DOTFILES_HOST_WORKSPACE:-..}:/workspace

name: dotfiles

services:
  ubuntu:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu
    command: sleep infinity

  fedora:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.fedora
    command: sleep infinity

  dev:
    <<: *default-service
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    entrypoint:
      - /usr/local/bin/dev-entrypoint.sh
    command:
      - /bin/bash
      - -l
    volumes:
      - ${DOTFILES_HOST_WORKSPACE:-..}:/workspace
      - ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/ssh-agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *default-env
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
      SSH_AUTH_SOCK: /ssh-agent
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
